nodejs:
  image: 'hmctspublic.azurecr.io/ds/ui:latest'
  applicationPort: 4000
  memoryRequests: 1Gi
  cpuRequests: 1000m
  memoryLimits: 2Gi
  cpuLimits: 2500m
  devmemoryRequests: 1Gi
  devcpuRequests: 1000m
  devmemoryLimits: 2Gi
  devcpuLimits: 2500m
  readinessDelay: 130
  livenessDelay: 130
  autoscaling: # Default is false
    enabled: true
    maxReplicas: 5 # Required setting
    targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization
  aadIdentityName: ds
  ingressHost: ds-ui.{{ .Values.global.environment }}.platform.hmcts.net

  environment:
    NODE_ENV: production
    REFORM_TEAM: ds
    REFORM_SERVICE_NAME: ds-ui

    SERVICE_AUTH_PROVIDER_URL: 'http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    IDAM_WEB_URL: 'https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login'
    IDAM_API_URL: 'https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/token'

  keyVaults:
    ds:
      secrets:
        - idam-secret
        - idam-ui-secret
        - idam-system-user-name
        - idam-system-user-password
        - redis-access-key
        - s2s-secret
        - AppInsightsInstrumentationKey