security:
  referrerPolicy: 'origin'
port: 3001
timeout: 300000
services:
  authProvider:
    url: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal'
    microservice: 'ds_ui'
    secret: 'NEED TO INSERT SECRET'
  # idam:
  #   authorizationURL: 'http://localhost:3501/login'
  #   tokenURL: 'http://localhost:5000/o/token'
  #   clientID: 'adoption-web'
  #   clientSecret: 'thUphEveC2Ekuqedaneh4jEcRuba4t2t'
  #   systemUsername: 'dummy_user'
  #   systemPassword: 'dummy_password'
  # case:
  #   url: 'http://localhost:4452'
  postcodeLookup:
    url: 'https://api.os.uk/search/places/v1'
    token: 'NEED TO INSERT SECRET'
  feeLookup:
    url: 'http://fees-register-api-aat.service.core-compute-aat.internal/fees-register/fees/lookup'
  hmctsHomePage:
    url: 'https://www.gov.uk/government/organisations/hm-courts-and-tribunals-service'
  documentManagement:
    url: 'http://fis-cos-api-pr-62.service.core-compute-preview.internal'  
    uploadSizeinMB: 30
  RPE_TOKEN:
    url: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal'      
health:
  timeout: 5000
  deadline: 15000
session:
  secret: 'local'
  redis:
    host:
    key:
e2e:
  userTestPassword: ''
appInsights:
  instrumentationKey:
