apiVersion: v2
appVersion: '1.0'
description: A Helm chart for fis-ds-web App
name: fis-ds-web
home: https://github.com/hmcts/fis-ds-web
version: 0.0.4
dependencies:
  - name: nodejs
    version: 2.4.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
